Improve delays
nrfconnect/sdk-hostap pull request #56
Opened 2023-01-19 14:14 UTC by krish2718

Instead of using sleep, switch to semaphore to avoid unnecessary extra loop.

2023-01-31 12:46 UTC, sachinthegreen requested changes

2023-01-31 12:46 UTC, sachinthegreen commented on src/drivers/driver_zephyr.c
> +		if_ctx->scan_res2_get_in_prog = true;
Do we need the else part here?

2023-01-31 12:46 UTC, sachinthegreen commented on src/drivers/driver_zephyr.c
> +
Do we need error handling here if there is a timeout?

2023-02-01 07:45 UTC, sachinthegreen approved these changes

2023-02-01 08:42 UTC, sr1dh48r approved these changes

2023-02-01 09:31 UTC, merged